# Generated by Django 4.2.1 on 2023-05-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('logo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('tla', models.CharField(max_length=3)),
                ('logo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('utcDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('FINISHED', 'FINISHED'), ('TIMED', 'TIMED'), ('LIVE', 'LIVE'), ('IN_PLAY', 'IN_PLAY'), ('POSTPONED', 'POSTPONED'), ('SUSPENDED', 'SUSPENDED'), ('CANCELLED', 'CANCELLED')], max_length=100)),
                ('matchday', models.IntegerField()),
                ('stage', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField()),
                ('winner', models.CharField(choices=[('1', 'HOME_TEAM'), ('X', 'DRAW'), ('2', 'AWAY_TEAM')], max_length=100)),
                ('duration', models.CharField(choices=[('REGULAR', 'REGULAR'), ('EXTRA_TIME', 'EXTRA_TIME'), ('PENALTY_SHOOTOUT', 'PENALTY_SHOOTOUT')], max_length=100)),
                ('fulltime_home', models.IntegerField()),
                ('fulltime_away', models.IntegerField()),
                ('halftime_home', models.IntegerField()),
                ('halftime_away', models.IntegerField()),
                ('referee', models.TextField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='data.team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.competition')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='data.team')),
            ],
        ),
    ]
