# Generated by Django 4.2.1 on 2023-05-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_match_fulltime_away_alter_match_fulltime_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fte_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
