# Generated by Django 4.2.1 on 2023-08-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('data', models.JSONField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('competition', models.CharField(max_length=5, verbose_name='Competition')),
                ('home_team_id', models.IntegerField(verbose_name='Home Team Id')),
                ('away_team_id', models.IntegerField(verbose_name='Away Team Id')),
                ('datetime', models.DateTimeField(verbose_name='Date Time')),
                ('data', models.JSONField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Scorers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=5, verbose_name='Competition')),
                ('data', models.JSONField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Scorers',
                'verbose_name_plural': 'Scorers',
            },
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=5, verbose_name='Competition')),
                ('data', models.JSONField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Standings',
                'verbose_name_plural': 'Standings',
            },
        ),
    ]
