# Generated by Django 4.2.3 on 2023-09-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team_id',
            field=models.IntegerField(null=True, verbose_name='Away Team Id'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_id',
            field=models.IntegerField(null=True, verbose_name='Home Team Id'),
        ),
    ]
