# Generated by Django 4.2.1 on 2023-07-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fivethirtyeight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballteam',
            name='defensive',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='defensive'),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='offensive',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='offensive'),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='spi',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='spi'),
        ),
    ]
