# Generated by Django 4.2.1 on 2023-07-17 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fivethirtyeight', '0002_alter_footballteam_defensive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballmatch',
            old_name='competition',
            new_name='league_id',
        ),
        migrations.RenameField(
            model_name='footballmatch',
            old_name='prob_home',
            new_name='prob1',
        ),
        migrations.RenameField(
            model_name='footballmatch',
            old_name='prob_away',
            new_name='prob2',
        ),
        migrations.RenameField(
            model_name='footballmatch',
            old_name='prob_draw',
            new_name='probtie',
        ),
        migrations.RenameField(
            model_name='footballmatch',
            old_name='fulltime_home',
            new_name='score1',
        ),
        migrations.RenameField(
            model_name='footballmatch',
            old_name='fulltime_away',
            new_name='score2',
        ),
        migrations.RenameField(
            model_name='footballmatch',
            old_name='home_team',
            new_name='team1',
        ),
        migrations.RenameField(
            model_name='footballmatch',
            old_name='away_team',
            new_name='team2',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='date',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='season',
        ),
        migrations.RemoveField(
            model_name='footballmatch',
            name='spi_home',
        ),
        migrations.AddField(
            model_name='footballcompetition',
            name='name_url',
            field=models.CharField(default='', max_length=200, verbose_name='name_url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballcompetition',
            name='season',
            field=models.CharField(default='2022', max_length=10, verbose_name='season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 19, 19, 9, 688873, tzinfo=datetime.timezone.utc), verbose_name='datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='group',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='group'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='leg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='matchday'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='matchday',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='matchday'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='round',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='round'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='status',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='footballteam',
            name='rank',
            field=models.PositiveIntegerField(default=1000, verbose_name='rank'),
            preserve_default=False,
        ),
    ]
