# Generated by Django 4.2.1 on 2023-07-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fivethirtyeight', '0005_alter_footballcompetition_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballcompetition',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
