# Generated by Django 4.2.1 on 2023-07-21 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fivethirtyeight', '0008_alter_footballcompetition_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballmatch',
            old_name='league_id',
            new_name='competition',
        ),
    ]
