# Generated by Django 4.2.1 on 2023-07-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fivethirtyeight', '0009_rename_league_id_footballmatch_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballcompetition',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='prob1',
            field=models.DecimalField(decimal_places=5, max_digits=6, verbose_name='prob_home'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='prob2',
            field=models.DecimalField(decimal_places=5, max_digits=6, verbose_name='prob_away'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='probtie',
            field=models.DecimalField(decimal_places=5, max_digits=6, verbose_name='prob_draw'),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
    ]
