# Generated by Django 4.2.1 on 2023-08-19 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fivethirtyeight', '0010_alter_footballcompetition_id_alter_footballmatch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballcompetition',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='footballcompetition',
            name='logo',
            field=models.URLField(blank=True, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='footballcompetition',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='footballcompetition',
            name='name_url',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='footballcompetition',
            name='season',
            field=models.CharField(max_length=10, verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='footballcompetition',
            name='standings',
            field=models.JSONField(blank=True, null=True, verbose_name='Standings'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fivethirtyeight.footballcompetition', verbose_name='Competition'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='datetime',
            field=models.DateTimeField(verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='group',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='leg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Leg'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='matchday',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Matchday'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='prob1',
            field=models.DecimalField(decimal_places=5, max_digits=6, verbose_name='Prob Home'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='prob2',
            field=models.DecimalField(decimal_places=5, max_digits=6, verbose_name='Prob Away'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='probtie',
            field=models.DecimalField(decimal_places=5, max_digits=6, verbose_name='Prob Draw'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='round',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='score1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fulltime Home'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='score2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fulltime Away'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='status',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='fivethirtyeight.footballteam', verbose_name='Home Team'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='fivethirtyeight.footballteam', verbose_name='Away Team'),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='defensive',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Defensive'),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='logo',
            field=models.URLField(blank=True, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='offensive',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Offensive'),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='rank',
            field=models.PositiveIntegerField(verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='footballteam',
            name='spi',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='SPI'),
        ),
    ]
